version: '3'
services:
  # Postgres
  postgres:
    image: postgres:latest
    ports:
      # Accessible from the host at port :35432
      - '35432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: saas
    # Make sure log colors show up correctly
    tty: true

  # Prisma Studio
  studio:
    build:
      context: .
      dockerfile: Dockerfile.studio
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/saas
    ports:
      - '5555:5555'
    # Make sure log colors show up correctly
    tty: true
